version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./dockerfiles/nestjs.dockerfile
    volumes:
      - /app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
  activemq:
    image: rmohr/activemq:latest
    ports:
      - "8161:8161"
      - "61616:61616"